girlGuidesProject/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from girlGuidesProject.SettingUtils import custom_discover
from django.conf import settings

#admin.autodiscover()
#List of apps to add to admin
whitelisted_apps = (
        'girlGuidesProject.events',
        'girlGuidesProject.members',
        'easy_maps',
        'girlGuidesProject',
        'girlGuidesProject.slideShow',
        'girlGuidesProject.newsletter',
        'girlGuidesProject.guideForms',
        'photologue',
    )
# #Custom discovery function registers only selected apps in admin 
custom_discover (whitelisted_apps)

urlpatterns = patterns('',
   url(r'^$', 'girlGuidesProject.views.home'),                   
   #Urls for login
   url(r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name': 'main/login.html'}),
   url(r'^accounts/logout/$', 'girlGuidesProject.views.logoutView'),
   url(r'^contactForm/',    include('envelope.urls')),
   url(r'^events/$',  'girlGuidesProject.events.views.eventList'  ),
   url(r'^events/id=(?P<id>\d{1,10})/$', 'girlGuidesProject.events.views.eventDetail', name = 'eventMap'),
   url(r'^newsletters/$',  'girlGuidesProject.newsletter.views.newsletterList'  ),
   url(r'^forms/$',  'girlGuidesProject.guideForms.views.formList'  ),
   url(r'^photologue/', include('photologue.urls')),

   url(r'^photologue/', include('photologue.urls')),

#    url(r'^newsletters/id=(?P<id>\d{1,4})$', 'newsletter.views.newsletterDetail'),

   url(r'^about/$',  'girlGuidesProject.views.aboutView' ),

   # Uncomment the next line to enable the admin:
   url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    urlpatterns += patterns('django.views.static',
        (r'media/(?P<path>.*)', 'serve', {'document_root': settings.MEDIA_ROOT}),
    )

girlGuidesProject/events/models.py
from django.db import models
#Includes for email format and send
from django.core.mail import EmailMultiAlternatives
from django.template.loader import get_template
from django.template import Context
from girlGuidesProject.members.models import guardian , scoutMember, scoutGroups, scoutLeader
from django.contrib.auth.models import User
from django.utils import formats


class Event(models.Model):
    title        = models.CharField(max_length=30)
    description  = models.CharField(max_length=100)
    start        = models.DateTimeField()
    end          = models.DateTimeField()
    address      = models.CharField(max_length=100,verbose_name='Event Address') #TODO OVERWRITE SAVE LIKE IN MEMBERS APP MODELS TO SEND EMAIL 
    #Specify group so that events just for youngest group for example only get email notifications to parents/members in that group
    scoutGroup   = models.ForeignKey(scoutGroups , verbose_name="Guide group") 
    
    
    #Function to return human readable name
    def __unicode__(self):
        start =  formats.date_format(self.start, "SHORT_DATETIME_FORMAT")
        end =  formats.date_format(self.end, "SHORT_DATETIME_FORMAT")
        #return u'%s -  %s until  %s' % (self.title,start,end)
        return u'%s' % (self.title)

   
   #Note this is called for record updates and new records inserts 
    def save(self, *args, **kwargs):
        # Set up variables for email that are common to all emails 

        subject               = 'Event Updated or Created'
        from_email            = 'donotreply@BlackMountainScouts.com'      
        htmlTemplate          =  get_template('events/EventEmail.html')
        plaintextTemplate     =  get_template('events/EventEmail.txt')     
        email_destination     =  self.getEmailDestination()       
       
        
        #If the obect primary keys is not null then we are updating an existing record
        if self.pk:                        
            #Loop through sending email
            #Note - send mass email is far more efficient but does seem to support html with txt
            # fall back + implementing it was problematic 
            # Note all emails need context set here
            
            for destination in email_destination:
                emailContext = Context({'event':self, 'edit':True})
                #Render templates
                text_content = plaintextTemplate.render(emailContext)
                html_content = htmlTemplate.render(emailContext)
                #Create and send msg
                msg = EmailMultiAlternatives(subject, html_content , from_email, [destination,])
                msg.attach_alternative(html_content,"text/html")
                msg.send()

        #if not self.pk the we are creating a new event    
        else:
            emailContext = Context({'event':self, 'create':True})
            #Render templates
            text_content = plaintextTemplate.render(emailContext)
            html_content = htmlTemplate.render(emailContext)
            #Build up list of emails to send
            #Loop through sending email
            #Note - send mass email is far more efficient but does seem to support html with txt
            # fall back + implementing it was problematic 
            # Note all emails need context set here
            for destination in email_destination:
                msg = EmailMultiAlternatives(subject, html_content , from_email, [destination,])
                msg.attach_alternative(html_content,"text/html")
                msg.send()

            
        #Call parent function to fo actual saving/update
        super(Event, self).save(*args, **kwargs) 

    def delete(self, *args, **kwargs):
        email_destination     =  self.getEmailDestination()      
        if self.pk: 
            subject               = 'Event Cancelled'
            from_email            = 'donotreply@BlackMountainScouts.com'      
            htmlTemplate          =  get_template('events/EventEmail.html')
            plaintextTemplate     =  get_template('events/EventEmail.txt')     
            email_destination     =  self.getEmailDestination()                           

            #Loop through sending email
            #Note - send mass email is far more efficient but does seem to support html with txt
            # fall back + implementing it was problematic 
            # Note all emails need context set here
            for destination in email_destination:
                emailContext = Context({'event':self, 'delete':True})
                #Render templates
                text_content = plaintextTemplate.render(emailContext)
                html_content = htmlTemplate.render(emailContext)
                #Create and send msg
                msg = EmailMultiAlternatives(subject, html_content , from_email, [destination,])
                msg.attach_alternative(html_content,"text/html")
                msg.send()
        #Call parent function to fo actual saving/update
        super(Event, self).delete(*args, **kwargs) 
                        
   
    #Retrieve parent and scout member emails if they one and the event is for them
    #Add all scout leaders to email list            
    def getEmailDestination(self):
        scoutMembersList      = scoutMember.objects.all()
        scoutLeaders          = scoutLeader.objects.all()
        email_destination     = []
        parents               = []
        #Find appropiate scout members to email them and their guardians about event
        for selectedScoutMember in scoutMembersList:             
            eventScoutGroup = self.scoutGroup
            if   eventScoutGroup.name == selectedScoutMember.scoutGroup.name or eventScoutGroup.name == 'All':
                parents  = selectedScoutMember.parents.all()
                for parent in parents:            
                    if parent.email:
                        email_destination.append(parent.email)
        #Add all scout leaders to event emails
        for leader in scoutLeaders:
            if leader.email:
                email_destination.append(leader.email)
                
        #Ensure no duplicate emails - sets are guaranteed to have no duplicates
        #so type cast to set to remove duplicates - and then back to list 
        email_destination = list(set(email_destination))     
        return email_destination           

                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                

girlGuidesProject/events/views.py
from girlGuidesProject.events.models import Event
from django.template import RequestContext, loader
from django.http import  *
from django.contrib.auth.decorators import login_required
from girlGuidesProject.tables import EventsTable
from django_tables2   import RequestConfig
from django.shortcuts import render
from datetime import datetime

@login_required
def eventList(request):
    if Event.objects.all().count() > 0:
        curEvents = Event.objects.filter(end__gte=datetime.today())
        table = EventsTable(curEvents)    
        RequestConfig(request).configure(table)
        return render(request, 'events/events.html', {'table': table, 'events':curEvents})
    else:
        return render(request, 'events/events.html', {'noResults': True})


@login_required
def eventDetail(request , id = 1 ):
    event        = Event.objects.get(pk = id)
    template     = loader.get_template('events/eventDetail.html') 
    context      = RequestContext(request,{'event':event})
        
    return HttpResponse(template.render(context))

girlGuidesProject/events/templates/events/EventEmail.html
<!DOCTYPE html>
<body >
{% if delete %}
	 The following event has been cancelled:<br>
	 Event Name  : {{event.title}}<br>
	 Location    : {{event.address}}<br>
	 Description : {{event.description}}<br>
	 Start Date  : {{event.start | date:"DATE_FORMAT"}}<br>
	 Start Time  : {{event.start |time:"TIME_FORMAT"}}<br>
	 End Date    : {{event.end | date:"DATE_FORMAT"}}<br>
	 End Time    : {{event.end |time:"TIME_FORMAT"}}<br>
	{% elif edit %}
	 The event, {{event.title}} has been changed:<br>
	 Details are as follows:<br>
	 Event Name  : {{event.title}}<br>
	 Location    : {{event.address}}<br>
	 Description : {{event.description}}<br>
	 Start Date  : {{event.start | date:"DATE_FORMAT"}}<br>
	 Start Time  : {{event.start |time:"TIME_FORMAT"}}<br>
	 End Date    : {{event.end | date:"DATE_FORMAT"}}<br>
	 End Time    : {{event.end |time:"TIME_FORMAT"}}<br>
	{% elif create %}
	 The following event has been created:<br>
	 Event Name  : {{event.title}}<br>
	 Location    : {{event.address}}<br>
	 Description : {{event.description}}<br>
	 Start Date  : {{event.start | date:"DATE_FORMAT"}}<br>
	 Start Time  : {{event.start |time:"TIME_FORMAT"}}<br>
	 End Date    : {{event.end | date:"DATE_FORMAT"}}<br>
	 End Time    : {{event.end |time:"TIME_FORMAT"}}<br>
{% endif %}
</body>
</html>

girlGuidesProject/events/templates/events/eventDetail.html
{% extends "main/base.html" %}
{% load staticfiles %}
{% block head %}
<script src="{%static 'main/js/google-maps-plugin.js' %}"></script>
   		<script src="{%static 'main/js/jquery-2.0.3.min.js' %}"></script>
      <script src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>
     <script src="{%static 'main/js/google-maps-plugin.js' %}"></script>
   

{% endblock head %}

{% block content %}

<h2>{{event.title}}</h2>
<p> Address: </p> <input class="vTextField" id="id_address" size="100" name="address" type="text" value='{{event.address}}' readonly><br>
<p>{{event.description}}</p><br />
Location: {{event.address}}<br />
Start Date: {{event.start | date:"DATE_FORMAT"}}<br>
Start Time: {{event.start |time:"TIME_FORMAT"}}<br>
End Date: {{event.end | date:"DATE_FORMAT"}}<br>
End Time: {{event.end |time:"TIME_FORMAT"}} <br>
Affected Groups: {{events.scoutGroup}}<br>

{% endblock content %}

girlGuidesProject/events/templates/events/eventMapModal.html
    
<div id ={{record.id}}
<p> Address: </p> <input class="vTextField" id="id_address" maxlength="100" name="address" type="text" value='{{event.address}}' readonly>
</div>
               

girlGuidesProject/events/templates/events/events.html
{% extends "main/base.html" %}
{% load render_table from django_tables2 %}
{% load staticfiles %}
{% block head%}

        <script src="{%static 'main/js/jquery-2.0.3.min.js' %}"></script>
      <script src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>
     <script src="{%static 'main/js/google-maps-plugin.js' %}"></script>
   

{% endblock head %}
 {% block content %}
 
    {% if not noResults %}
    <div id="table" class="grid_13">
        {% render_table table %}
    </div>    
    {% else %}
        <h1> No current events,please check back soon.</h1>
    {% endif %}
    
    
 {% endblock %}			